import {
  faStethoscope,
  faTooth,
  faSyringe,
  faPills,
  faHandHoldingMedical,
  faGear,
  faBriefcase,
  faScaleBalanced,
  faPlane,
  faShieldHalved,
  faChalkboardUser,
  faLandmark,
  faGraduationCap,
  faRobot,
  faBookOpen,
  faBullseye,
  faClipboardList,
  faLink,
  faCompass,
  faCircleCheck,
  faFlag,
  faSackDollar,
  faBell,
  faUsers,
  faLightbulb,
  faRocket,
  faPhone,
  faHeart,
} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  stethoscope: faStethoscope,
  tooth: faTooth,
  syringe: faSyringe,
  pills: faPills,
  "hand-holding-medical": faHandHoldingMedical,
  gear: faGear,
  briefcase: faBriefcase,
  "scale-balanced": faScaleBalanced,
  plane: faPlane,
  "shield-halved": faShieldHalved,
  "chalkboard-user": faChalkboardUser,
  landmark: faLandmark,
  "graduation-cap": faGraduationCap,
  robot: faRobot,
  "book-open": faBookOpen,
  bullseye: faBullseye,
  "clipboard-list": faClipboardList,
  link: faLink,
  compass: faCompass,
  "circle-check": faCircleCheck,
  flag: faFlag,
  "sack-dollar": faSackDollar,
  bell: faBell,
  users: faUsers,
  lightbulb: faLightbulb,
  rocket: faRocket,
  phone: faPhone,
  heart: faHeart,
};

export type IconName = keyof typeof icons;
